---
# Jobs to be executed
jobs:
  - name: email-notification
    public: true
    serial: true
    plan:
      - get: my-git-project
      - put: email-notification
        params:
          input_dir: my-git-project
          email_body: {{email_body}}

resources:
  - name: my-git-project
    type: git
    source:
      uri: <Specify-Git-URL-of-the-Project>
      branch: master
      private_key: {{github_key}}

  - name: email-notification
    type: email-notification-resource
    source:
      smtp_host: "<SMTP-Host>"
      smtp_port: "<SMTP-Port>"
      smtp_username: {{smtp_user}}
      smtp_password: {{smtp_password}}
      default_recipient: "<Default-Recepient-Email-ID>"

resource_types:
  - name: email-notification-resource
    type: docker-image
    source:
      repository: santoshjpawar/concourse-email-notification
      tag: latest